---
kind: pipeline
type: ssh
name: default

server:
  host: noj.tw
  user: development
  ssh_key:
    from_secret: ssh_key

steps:
- name: test
  commands:
  - echo "testing..."

- name: New Master
  commands:
  - echo "Master!"
  when:
    event:
    - push
    branch:
    - master
