services:
  caddy:
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./.config/Caddyfile.prod:/etc/caddy/Caddyfile
      - ./.caddy:/data
    env_file:
      - .secret/caddy.env
  mongo:
    restart: unless-stopped
  mongo-express:
    restart: unless-stopped
    env_file:
      - .secret/mongo-express.env
  web:
    image: ${WEB_IMAGE:-asia-east1-docker.pkg.dev/noj-team1/backend/noj-web:latest}
    restart: unless-stopped
    env_file:
      - .secret/web.env
    volumes:
      - ./Back-End/gunicorn_error.log:/app/gunicorn_error.log
  sandbox:
    image: ${SANDBOX_IMAGE:-asia-east1-docker.pkg.dev/noj-team1/sandbox/noj-sandbox:latest}
    restart: unless-stopped
    env_file:
      - .secret/sandbox.env
    volumes:
      - ./Sandbox/submissions:/app/submissions
      - ./Sandbox/logs:/app/logs
  redis:
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    restart: unless-stopped
    env_file:
      - .secret/minio.env
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - /opt/noj/minio:/data
