version: '3'

services:

  caddy:
    image: abiosoft/caddy
    environment:
      - ACME_AGREE=true

  mongo:
    image: mongo
    volumes:
      - ./MongoDB:/data/db

  mongo-express:
    image: mongo-express
    restart: always

  vue:
    build: ./Front-End

  web:
    build: ./Back-End
    environment:
      - MONGO_HOST=mongo
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  sandbox:
    build: ./Sandbox
    volumes:
      - ./Sandbox:/app
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/var/lib/redis
