version: "3"

services:
  caddy:
    image: caddy

  mongo:
    image: mongo
    volumes:
      - ./MongoDB:/data/db

  mongo-express:
    image: mongo-express
    restart: always

  vue:
    build: ./Front-End

  web:
    build: ./Back-End
    environment:
      - MONGO_HOST=mongo

  sandbox:
    build: ./Sandbox
    volumes:
      - ./Sandbox:/app
      - /var/run/docker.sock:/var/run/docker.sock
