version: '2'

services:

  caddy:
    image: abiosoft/caddy
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./.caddy:/root/.caddy
    ports:
      - "8080:8080"
      - "8081:8081"
      - "80:80"
      - "443:443"
    environment:
      - ACME_AGREE=true

  mongo:
    image: mongo
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    env_file:
      - ./mongo-express.env

  vue:
    build: ./Front-End

  web:
    build: ./Back-End
    restart: always
    volumes:
      - ./Back-End:/code
    env_file:
      - ./Back-End/flask.env
