services:
  caddy:
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./.config/Caddyfile.prod:/etc/caddy/Caddyfile
      - ./.caddy:/data
    env_file:
      - .secret/caddy.env
  mongo:
    restart: unless-stopped
  mongo-express:
    restart: unless-stopped
    env_file:
      - .secret/mongo-express.env
  web:
    build:
      target: production
    restart: unless-stopped
    env_file:
      - .secret/web.env
    volumes:
      - ./Back-End/gunicorn_error.log:/app/gunicorn_error.log
  sandbox:
    build:
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file:
      - .secret/sandbox.env
    volumes:
      - ./Sandbox/submissions:/app/submissions
      - ./Sandbox/logs:/app/logs
  redis:
    restart: unless-stopped
